### ISSUE TITLE
Java?

### ISSUE THREAD

**Issue by Cassie4335** [likitha-9/Keyword-Crawler#3]
Hi!
Can I ask why you’re using Java at all? Wouldn’t it kinda be easier to just do everything in Python.?

**Comment by Cassie4335** [comment]
Or Java? Why crosslink languages at all?

**Comment by likitha-9** [comment]
Hi, Cassie,
In all honestly, for no specific reason really. I used Java mostly for the JavaFX library and I'm using Python for the web scraping part. I never crosslinked high-level programming languages before, so I suppose I just wanted to try and learn something new!
